import React, { useState, useRef }  from "react";
import "./index.css";
import axios from "axios";
import Tabela from "../Tabela";

export default function Form(props) {
  const {atualizaPais} = props;
        const [pais, setPais] = useState('');
        const handleChange = (event) => {
          setPais(event.target.value);
        };
        const salvarPais = (event) => {
            event.preventDefault();
            // props.carregaPaises();
            setPais("");
        }

        const paises = [
          'Afeganistão',
          'África do Sul',
          'Albânia',
          'Alemanha',
          'Andorra',
          'Angola',
          'Antígua e Barbuda',
          'Arábia Saudita',
          'Argélia',
          'Argentina',
          'Armênia',
          'Austrália',
          'Áustria',
          'Azerbaijão',
          'Bahamas',
          'Bahrein',
          'Bangladesh',
          'Barbados',
          'Belarus (Bielorrússia)',
          'Bélgica',
          'Belize',
          'Benin',
          'Butão',
          'Bolívia',
          'Bósnia e Herzegovina',
          'Botsuana',
          'Brasil',
          'Brunei',
          'Bulgária',
          'Burkina Faso',
          'Burundi',
          'Cabo Verde',
          'Camboja',
          'Camarões',
          'Canadá',
          'Catar',
          'Cazaquistão',
          'Chade',
          'Chile',
          'China',
          'Chipre',
          'Colômbia',
          'Comores',
          'Congo-Brazzaville',
          'Congo-Kinshasa',
          'Coreia do Norte',
          'Coreia do Sul',
          'Costa do Marfim',
          'Costa Rica',
          'Croácia',
          'Cuba',
          'Dinamarca',
          'Djibuti',
          'Dominica',
          'Egito',
          'El Salvador',
          'Emirados Árabes Unidos',
          'Equador',
          'Eritreia',
          'Eslováquia',
          'Eslovênia',
          'Espanha',
          'Estados Unidos',
          'Estônia',
          'Eswatini',
          'Etiópia',
          'Fiji',
          'Filipinas',
          'Finlândia',
          'França',
          'Gabão',
          'Gâmbia',
          'Gana',
          'Geórgia',
          'Granada',
          'Grécia',
          'Guatemala',
          'Guiana',
          'Guiné',
          'Guiné Equatorial',
          'Guiné-Bissau',
          'Haiti',
          'Honduras',
          'Hungria',
          'Iêmen',
          'Ilhas Marshall',
          'Ilhas Salomão',
          'Índia',
          'Indonésia',
          'Irã',
          'Iraque',
          'Irlanda',
          'Islândia',
          'Israel',
          'Itália',
          'Jamaica',
          'Japão',
          'Jordânia',
          'Kiribati',
          'Kosovo',
          'Kuwait',
          'Laos',
          'Lesoto',
          'Letônia',
          'Líbano',
          'Libéria',
          'Líbia',
          'Liechtenstein',
          'Lituânia',
          'Luxemburgo',
          'Macedônia do Norte',
          'Madagascar',
          'Malásia',
          'Malaui',
          'Maldivas',
          'Mali',
          'Malta',
          'Marrocos',
          'Maurício',
          'Mauritânia',
          'México',
          'Micronésia',
          'Moçambique',
          'Moldávia',
          'Mônaco',
          'Mongólia',
          'Montenegro',
          'Myanmar (Birmânia)',
          'Namíbia',
          'Nauru',
          'Nepal',
          'Nicarágua',
          'Níger',
          'Nigéria',
          'Noruega',
          'Nova Zelândia',
          'Omã',
          'Países Baixos (Holanda)',
          'Palau',
          'Panamá',
          'Papua Nova Guiné',
          'Paquistão',
          'Paraguai',
          'Peru',
          'Polônia',
          'Portugal',
          'Quênia',
          'Quirguistão',
          'Reino Unido',
          'República Centro-Africana',
          'República Dominicana',
          'República Tcheca',
          'Romênia',
          'Rússia',
          'Ruanda',
          'Saara Ocidental',
          'Saint Kitts e Nevis',
          'Saint Vincent e Granadinas',
          'Saint-Barthélemy',
          'Saint-Martin',
          'Samoa',
          'San Marino',
          'Santa Lúcia',
          'São Cristóvão e Nevis',
          'São Tomé e Príncipe',
          'Senegal',
          'Serra Leoa',
          'Sérvia',
          'Seychelles',
          'Singapura',
          'Síria',
          'Somália',
          'Sri Lanka',
          'Suazilândia',
          'Sudão',
          'Sudão do Sul',
          'Suécia',
          'Suíça',
          'Suriname',
          'Tailândia',
          'Taiwan',
          'Tajiquistão',
          'Tanzânia',
          'Timor-Leste (Timor Oriental)',
          'Togo',
          'Tonga',
          'Trinidad e Tobago',
          'Tunísia',
          'Turcomenistão',
          'Turquia',
          'Tuvalu',
          'Ucrânia',
          'Uganda',
          'Uruguai',
          'Uzbequistão',
          'Vanuatu',
          'Vaticano',
          'Venezuela',
          'Vietnã',
          'Zâmbia',
          'Zimbábue'
        ];
        
  return (
    <form className="form-card" onSubmit={salvarPais}>
      <input className="form-card-title" type="text"  name="pais"  onChange={(e)=>setPais(e.target.value)} placeholder="Digite o nome do país" aria-autocomplete="list" list="paises-lista" />
      <datalist id="paises-lista">
        {paises.map((pais, index) => (
          <option key={index} value={pais} />
        ))}
      </datalist>
      <button className="btn" onClick={()=>atualizaPais(pais)} type="submit">ir</button>
    </form>
  );

}
